# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruby-poker}
  s.version = "0.3.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rob Olson"]
  s.date = %q{2009-10-28}
  s.description = %q{Ruby library for comparing poker hands and determining the winner.}
  s.email = %q{rob@thinkingdigitally.com}
  s.extra_rdoc_files = [
    "CHANGELOG",
     "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "CHANGELOG",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "examples/deck.rb",
     "examples/quick_example.rb",
     "lib/ruby-poker.rb",
     "lib/ruby-poker/card.rb",
     "lib/ruby-poker/combinatoria.rb",
     "lib/ruby-poker/odds.rb",
     "lib/ruby-poker/poker_hand.rb"
  ]
  s.homepage = %q{http://github.com/robolson/ruby-poker}
  s.rdoc_options = ["--charset=UTF-8", "--title", "Ruby Poker Documentation", "--main", "README.rdoc", "--inline-source", "-q"]
  s.require_paths = ["lib", "lib"]
  s.rubyforge_project = %q{rubypoker}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Poker library in Ruby}
  s.test_files = [
    "test/test_helper.rb",
     "test/test_card.rb",
     "test/test_poker_hand.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, ["> 2.0.0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, ["> 2.0.0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, ["> 2.0.0"])
  end
end
